SELECT *
FROM TBL_PRODUCT;

INSERT INTO TBL_PRODUCT 
VALUES(SEQ_POST.NEXTVAL, #{productName} , #{productPrice}, #{productSeller})

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER,
	PRODUCT_SELLER VARCHAR2(255) NOT NULL
);


UPDATE TBL_PRODUCT
SET PRODUCT_NAME = #{productName},
	PRODUCT_PRICE = #{productName}
	PRODUCT_STOCK = #{productSeller}
WHERE ID = #{id}


SELECT ID, #{productName}, #{productPrice}, #{productStock}
FROM TBL_PRODUCT 
WHERE ID = #{id}

SELECT 

