CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER ,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

SELECT *
FROM TBL_PRODUCT;

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 3;

UPDATE TBL_PRODUCT 
SET 
	PRODUCT_NAME = #{productName}, 
	PRODUCT_PRICE = #{productPrice},
	PRODUCT_STOCK = #{productStock}
WHERE ID = #{id}


DELETE 
FROM TBL_PRODUCT
WHERE ID = #{id};


-- 
CREATE SEQUENCE SEQ_POST;	
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL
);

SELECT *
FROM TBL_POST;

INSERT INTO TBL_POST 
VALUES(SEQ_POST.NEXTVAL,"제목", "내용");

SELECT POST_TITLE, POST_CONTENT
FROM TBL_POST;

-- MVC 2 패턴 POST 게시판 CRUD
-- 1. 게시글 작성
-- 2. 게시글 목록
-- 3. 게시글 상세보기
-- 4. 게시글 수정
-- 5. 게시글 삭제

