CREATE TABLE TBL_USER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_NAME VARCHAR2(255),
   USER_AGE NUMBER,
   USER_ADDRESS VARCHAR(255)
);

-- 상품 PRODUCT
-- 상품이름, 상품가격, 상품재고, 상품설명
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
   PRODUCT_PRICE NUMBER NOT NULL,
   PRODUCT_STOCK NUMBER DEFAULT 999,
   PRODUCT_DESCRIPE VARCHAR2(255)
);

-- SQL언어의 값은 '' 싱글쿼터를 사용한다.
INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '이승찬의 맥북', 1500000);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '배승원의 그램3', 150);

--DROP TABLE TBL_PRODUCT;
--DROP SEQUENCE SEQ_PRODUCT;

SELECT * FROM TBL_PRODUCT;

-- 컬럼 추가
ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER;

-- 컬럼 수정
ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0;

-- 컬럼 삭제
ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT;

-- MEMBER 테이블
-- ID, 이름, 나이, 성별, 주소
-- ID는 시퀀스로 관리
-- 사용자를 2명 추가
-- 등급 컬럼 CHAR 타입으로 추가
-- 등급 컬럼을 VARCAHR2 타입으로 변경
-- 등급 컬럼 삭제

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR(255) NOT NULL,
	MEMBER_AGE NUMBER NOT NULL,
	MEMBER_GENDER VARCHAR(255) NOT NULL,
	MEMBER_ADDRESS VARCHAR(255) NOT NULL
);

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES TBL_MEMBER(SEQ_PRODUCT.NEXTVAL,"홍길동", 20, "남성", "경기 화성");

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES TBLS_MEMBER(SEQ_PRODUCT.NEXTVAL , "윤한민", 27, "남성", "경기 성남");











