CREATE TABLE TBL_USER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_NAME VARCHAR2(255),
   USER_AGE NUMBER,
   USER_ADDRESS VARCHAR(255)
);

	
-- 상품 PRODUCT
-- 상품이름, 상품가격, 상품재고, 상품설명
CREATE SEQUENCE SEQ_PRODUCT; 
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
   PRODUCT_PRICE NUMBER NOT NULL,
   PRODUCT_STOCK NUMBER DEFAULT 999 ,
   PRODUCT_DESCRIPE VARCHAR2(255) 
);

-- SQL언어의 값은 '' 싱글쿼터를 사용한다.
INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DESCRIPE)
VALUES(SEQ_PRODUCT.NEXTVAL, '이승찬의 맥북', 1500000, '맥북에 대한 설명');

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DESCRIPE )
VALUES(SEQ_PRODUCT.NEXTVAL, '배승원의 그램4', 1500, '그램에 대한 설명');


--DROP TABLE TBL_PRODUCT;
--DROP SEQUENCE SEQ_PRODUCT;

SELECT * FROM TBL_PRODUCT;

-- 컬럼 추가
ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER;

-- 컬럼 수정
ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0; -- 다음 데이터부터 디폴트 적용

-- 컬럼 삭제
ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT;
	
-- MEMBER 테이블
-- ID, 이름, 나이, 성별, 주소
-- ID는 시퀀스로 관리
-- 사용자를 2명 추가
-- 등급 컬럼 CHAR 타입으로 추가
-- 등급 컬럼을 VARCAHR2 타입으로 변경
-- 등급 컬럼 삭제

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR(255) NOT NULL,
	MEMBER_AGE NUMBER NOT NULL,
	MEMBER_GENDER VARCHAR(255) NOT NULL,
	MEMBER_ADDRESS VARCHAR(255) NOT NULL
);

SELECT * FROM TBL_MEMBER;

--DROP TABLE TBL_MEMBER;
--DROP SEQUENCE SEQ_MEMBER;

-- 사용자 2명 추가
INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '박용우', 29, '남성', '서울시 강남구');

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '손흥민', 24, '남성', '춘천시 후평동');

-- 등급 컬럼 CHAR 타입으로 추가
ALTER TABLE TBL_MEMBER ADD GRADE CHAR(1);

-- 등급 컬럼을 VARCAHR2 타입으로 변경
ALTER TABLE TBL_MEMBER MODIFY GRADE VARCHAR2(255);

-- 등급 컬럼 삭제
ALTER TABLE TBL_MEMBER DROP COLUMN GRADE;







